# Generated by Django 3.1.7 on 2021-07-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='notes',
            field=models.JSONField(),
        ),
    ]
