# Generated by Django 3.1.7 on 2021-03-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronombre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronombre', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Verbotipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbotipo', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=32)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_v', to='verbos.verbotipo')),
            ],
        ),
        migrations.CreateModel(
            name='Conjugacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjugacion', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('pronombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronombre_c', to='verbos.pronombre')),
                ('tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_c', to='verbos.tiempo')),
                ('verbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbo_c', to='verbos.verbo')),
            ],
        ),
    ]
