# Generated by Django 3.1.7 on 2021-05-05 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbos', '0007_auto_20210427_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabrafecha',
            name='palabrafecha',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
